config/routes.rb
Rails.application.routes.draw do
  
  root "fronted#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :bugs do 
    resources :comments
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.blank?
      cannot :manage, :all
      basic_read_only
    elsif user.user? 
      cannot :manage, :all
      can :read, :all
      can :create, Bug
      can :destroy, Bug do |bug|
        bug.user_id == user.id
      end

    elsif user.developer?
      can :manage, :all
      
    end
 

  end

  private

  def basic_read_only 
    can :read, Bug
    can :read, Comment
  end
end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  
  enum status: {unread: 0, in_process: 1, done: 2}

  validates :title, :body, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bug
  belongs_to :user
  
  enum change_status: {unread: 0, in_process: 1, done: 2}
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :bugs
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:google_oauth2]
   
   def developer?
     return self.role == 0
   end
   
   def user?
     return self.role == 1
   end

   def self.from_omniauth(access_token)
     data = access_token.info
     user = User.where(:email => data["email"]).first
     unless user
       user = User.create(name: data["name"],
            email: data["email"],
            password: Devise.friendly_token[0,20])
     end
     user
   end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions
  force_ssl if: :ssl_configured?

  
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protect_from_forgery with: :exception

  protected
  def ssl_configured?
    !Rails.env.development?
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:sign_up) << :role
    devise_parameter_sanitizer.for(:account_update) << :role
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController


  def index
    @bugs = Bug.all.order(created_at: :desc)
  end

  def show
    @bug = Bug.find(params[:id])
    @statuses = Bug.statuses

    
  end

  def new
    @bug = current_user.bugs.create()
  end

  def create
    @bug = current_user.bugs.create(bug_params)
    @bug.status = params[:bug][:status].to_i
    if @bug.save
      redirect_to bug_path(@bug)
    else

      render :new, :notice => "請確認所有欄位都已經填寫完畢" 
    end
  end

  def update
    @bug = Bug.find(params[:id])
    @statuses = Bug.statuses

    if @bug.update!(bug_params)
      redirect_to bug_path(@bug)
    end
  end
  
  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    
    redirect_to root_path
  end

  private

  def set_bug
    @bug = Bug.find(params[:id])
  end

  def bug_params
    params[:bug].permit(:title, :body,:status, :filepicker_url)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@bug = Bug.find(params[:bug_id])
  	@comment = @bug.comments.create(comment_params)
  	@comment.bug.status = @comment[:change_status]
  	@status = Comment.change_statuses


  	if @comment.save && @comment.bug.save
  		redirect_to bug_path(@bug)
  	end

  end

  private

  def comment_params
  	params[:comment].permit(:content, :change_status)
  end
  
end

app/controllers/fronted_controller.rb
class FrontedController < ApplicationController
  def index
  	@bugs = Bug.includes(:user).order(created_at: :desc)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        flash[:notice] = "please ensure you're the one of sudo."
        redirect_to root_path
      end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page
  	return params[:controller] + "#" +  params[:action]
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fronted_helper.rb
module FrontedHelper
  def convert_chinese(bug)
  	if bug.status == 'unread'
  		return "未讀/尚未解決"
  	elsif bug.status == 'in_process'
  		return "解決中"
  	else
  		return "已解決"
  	end	
  end

  def convert_change_status(comment)
  	if comment.change_status == 'unread'
  		return "未讀/尚未解決"
  	elsif comment.change_status == 'in_process'
  		return "解決中"
  	else
  		return "已解決"
  	end	
  end
end

app/views/bugs/index.html.erb
<div class="row">
  <% @bugs.each do |bug| %>
  <div class="col s12 m6 l4">
    <%= link_to bug_path(bug) do %>
  	<div class="card  card-panel bug_card blue-grey">
  		<div class="card-content">
  			<span class="card-title"><%= bug.title %></span>
  			<li>狀態: <%= convert_chinese(bug) %></li>
        <li>回報者: <%= bug.user.name %></li>
  		</div>
  	</div>
  	<% end %>
  </div>
  <% end %>
</div>

app/views/bugs/new.html.erb
<div id="bug#new">
	<div class="row">
	  <div class="col s12 m12 l8 offset-l2">
		<%= simple_form_for @bug, :html => {:class => 'form'} do |f| %>
		
		<br>

		<%= f.input :title, label: "名稱" %>
		<div id="bug_input">
		  
		  <%= f.input :body, label: "BUG詳細內容" %>
		  <div id="epiceditor"></div>
		</div>
		<%= f.filepicker_field :filepicker_url %>
		<%= f.submit '送出', class: "btn " %>
		<% end %>
	  </div>
	</div>
</div>

<%= content_for :javascripts %>
<%= javascript_include_tag "bundle/bug_show_bundle.js" %>

app/views/bugs/show.html.erb
<div class="row">
  <h4><%= @bug.title %></h4>
	
  <div class="col s12 m12 l12">
    <% if @bug.filepicker_url.present? %>
    <div class="image_container">
      <%= image_tag @bug.filepicker_url %>
    </div>
    <% end %>
    <article class="content_area">
      <%= simple_format @bug.body %>    
    </article>
  </div>
  
  
</div>

<div class="row">
  <h5>開發者筆記</h5>
  <%= render @bug.comments.order(created_at: :desc) %>
  
</div>

<div class="row">
  <% if can? Comment,:manage %>
  <%= render 'partial/form' %>
  <% end %>
</div>
<%= content_for :javascripts %>
<%= javascript_include_tag "bundle/comment_form_bundle.js" %>

app/views/comments/_comment.html.erb
<div class="col s12 m6 l4">
  <article class="card-panel article_area">
    <h5><%= comment.bug.user.name %></h5>
    <%= simple_format comment.content %>

    <span>狀態：<%= convert_change_status(comment) %></span>
  </article>
</div>

app/views/fronted/index.html.erb
<div class="row center">
  <a href="#" id="showAll" class="btn">BUG列表</a>
  <a href="#" class="btn filters" data-filter="unread">未處理</a>
  <a href="#" class="btn filters" data-filter="in_process">處理中</a>
  <a href="#" class="btn filters" data-filter="done">已解決</a>
  
  
</div>

<div class="row">
  <table class="striped">
  	<thead>
  	  <tr>
  	    <td><h5>回報者</h5></td>
  	  	<td><h5>BUG主旨</h5></td>
  	  	<td><h5>內容</h5></td>
  	  	<td><h5>狀態</h5></td>
        <td></td>
  	  </tr>
  	</thead>
  	<tbody>
  	<% @bugs.each do |bug| %>
  	  <tr>
        <td><%= bug.user.name %></td>
  	  	<td><%= bug.title %></td>
        <td><%= link_to '詳細內容', bug_path(bug) %></td>
  	  	<td data-status="<%= bug.status %>"><%= convert_chinese(bug) %></td>
        <% if can? :destroy, Bug %>
        <td><%= link_to '刪除', bug_path(bug), :method => 'delete' %></td>
        <% end %>
  	  </tr>
  	<% end %>
  	</tbody>
  </table>
</div>

<div class="row">
  <div class="col s12 m12 l12 center">
    <%= link_to '我有bug', new_bug_path, class: "btn" %>
  <%= link_to '我要debug', bugs_path, class: "btn" %>
  </div>  
</div>



<%= content_for :javascripts %>
<%= javascript_include_tag "bundle/fronted_index_bundle.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bugu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav id="bug_navbar">
    
      <% if !user_signed_in? %>
      <ul class="right">
        <li><%= link_to "快速登入", user_omniauth_authorize_path(:google_oauth2) %></li>
      </ul>
      <% else %>
      <ul class="right"><li><%= link_to '登出', destroy_user_session_path, method: :delete %></li></ul>
      <ul class="left">
        <li><%= link_to '回到首頁', root_path %></li>  
      </ul>
      <% end %>
    
  </nav>
</header>
<div id="<%= current_page %>" class="fullpage">	
<div class="container">
  <%= yield %>	
</div>
</div>
<% if Rails.env.development? %>
  <%= debug params %>
<% end %>
<%= flash[:notice] %>
</body>
<% if notice != nil %>
<script>
  
  Materialize.toast('<%= flash[:notice] %>',4000,'rounded');
 
</script>
<% end %>
<%= yield :javascripts %>
<%= filepicker_js_include_tag %>
</html>

app/views/partial/_form.html.erb
<%= form_for([@bug, comment = @bug.comments.build]) do |f|%>
  <div id="bug_input">
  	<div id="epiceditor"></div>
  	<%= f.text_field :content %>
  	<div id="b_selectbox">
  	<%= f.select :change_status, options_for_select(@statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @bug.status), {} , class: "form-control" %>
  	
       
  	</div>
  	<%= f.submit '送出',class: 'btn',id: 'comment-button' %>
  </div>
<% end %>